language: java

install:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.6.5/2.12-1.6.5) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'

script:
  - amm -p predef.sc build.sc generate $(dirname $TRAVIS_REPO_SLUG) $(basename $TRAVIS_REPO_SLUG) $GITHUB_TOKEN $SITE

after_success:  
  - cd _site
  - git init
  - git config user.name $(dirname $TRAVIS_REPO_SLUG)
  - git config user.email $USER_EMAIL
  - git add .
  - git commit -m 'Generate site.'
  - git push -f "https://${GITHUB_TOKEN}@github.com/$USER_NAME/$REPO" master:master
