# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 放着, 我来
description: ""
baseurl: ""
url: "http://zhongl.github.io"

# Build settings
markdown: kramdown

gems:
   - jekyll-archives
   - jekyll-sitemap
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-feed

jekyll-archives:
  enabled:
     - categories