# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               '放着，我来'
tagline:             'by zhongl'
description:         '理想和情怀是有代价的, 但好在它不是自由的枷锁, 而应该是真正的自由本身. by <a href="https://github.com/dcaoyuan" target="_blank">@dcaoyuan</a>'
url:                 https://zhongl.github.io
baseurl:             ''
paginate:            5

exclude:
   - README.md
   - LICENSE.md

# About/contact
author:
  name:              Zhongl
  url:               https://github.com/zhongl
  email:             zhong.lunfu@gmail.com

# Custom vars
version:             1.0.0

gems:
   - jekyll-paginate
   - jekyll-gist
