# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               '放着，我来'
tagline:             'by zhongl'
description:         '理想和情怀是有代价的, 但好在它不是自由的枷锁, 而应该是真正的自由本身. by <a href="https://github.com/dcaoyuan" target="_blank">@dcaoyuan</a>'
url:                 https://zhongl.github.io
baseurl:             ''
paginate:            5
paginate_path:       'p/:num'

markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
   - README.md
   - LICENSE.md
   - Gemfile
   - Gemfile.lock
   - .gitignore

gems:
   - jekyll-paginate
   - jekyll-gist
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-feed
